apiVersion: v1
kind: Namespace
metadata:
  name: ingress-namespace
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  namespace: ingress-namespace
  labels:
    run: echo
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    run: echo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo-deployment
  namespace: ingress-namespace
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: echo
    spec:
      containers:
      - name: echo-pod
        image: echo:v1
        ports:
        - containerPort: 3000
          protocol: TCP
