apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-node
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: hello-node
    spec:
      containers:
      - name: hello-node
        image: hello-node:v2
        ports:
        - containerPort: 9000
          protocol: TCP
        env:
        - name: GREETING
          value: "Hello World Env Var"
