apiVersion: v1
kind: Service
metadata:
  name: hello-node-service
  labels:
    run: hello-node
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    run: hello-node
