apiVersion: v1
kind: Service
metadata:
  name: hello-node
  labels:
    run: hello-node
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    run: hello-node
