---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    run: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    run: mongo
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: mongo
    spec:
      containers:
      - name: mongo-pod
        image: mongo:v1
        ports:
        - containerPort: 27017
