apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: mongo
    spec:
      containers:
      - name: mongo-pod
        image: mongo:v1
        ports:
        - containerPort: 27017
          protocol: TCP
