apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    run: mongo
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    run: mongo
